version: "3.6"

services:
  MysqlData:
    image: busybox
    volumes:
      - ./database/mysql-data:/var/lib/mysql
  db:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: unless-stopped
    expose:
        - 3306
    volumes_from:
      - "MysqlData"
    environment:
      # These password and stuff is not neccesarry too secret
      - MYSQL_ROOT_PASSWORD=45299417d86f231f6a58434488edb763
      - MYSQL_DATABASE=ptit_shop
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - TZ=Asia/Ho_Chi_Minh
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8091:80

  webadmin:
    build: ./src/webadmin
    restart: 'always'
    ports:
      - "8090:80"
    environment:
      # These password and stuff is not neccesarry too secret
      - MYSQL_HOSTNAME=db
      - MYSQL_ROOT_PASSWORD=45299417d86f231f6a584d1488edb763
      - MYSQL_DATABASE=ptit_shop
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - "./src/webadmin:/var/www/html/"
  webshopping:
    build: ./src/webshopping
    restart: 'always'
    ports:
      - "8092:80"
    environment:
      # These password and stuff is not neccesarry too secret
      - MYSQL_HOSTNAME=db
      - MYSQL_ROOT_PASSWORD=45299417d86f231f6a584d1488edb763
      - MYSQL_DATABASE=ptit_shop
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - "./src/webshopping:/var/www/html/"
      - "./src/webadmin/public/products:/var/www/html/public/products"