apiVersion : apps/v1
kind: Deployment
metadata:
  name: workncwebshop 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workncwebshop
  template:
    metadata:
      labels:
        app: workncwebshop 
    spec:
      containers:
        - name: workncwebshop 
          image: n3tregistry.azurecr.io/workncwebshop
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOSTNAME
              value: $(MYSQL_HOSTNAME)
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: ptit_shop
            - name: MYSQL_USER
              value: $MYSQL_USER
            - name: MYSQL_PASSWORD
              value: $MYSQL_PASSWORD
            - name: TZ
              value: Asia/Ho_Chi_Minh
