apiVersion : apps/v1
kind: Deployment
metadata:
  name: workncwebshop 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workncwebshop
  template:
    metadata:
      labels:
        app: workncwebshop 
    spec:
      containers:
        - name: workncwebshop 
          image: n3tregistry.azurecr.io/workncwebshop
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOSTNAME
              value: 10.0.157.164
            - name: MYSQL_ROOT_PASSWORD
              value: 5299417d86f231f6a58434488edb763
            - name: MYSQL_DATABASE
              value: ptit_shop
            - name: MYSQL_USER
              value: db_user
            - name: MYSQL_PASSWORD
              value: db_password
            - name: TZ
              value: Asia/Ho_Chi_Minh
