apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  volumeMode: Filesystem
  hostPath:
    path: /mnt/disks/azure-disk 
    type: DirectoryOrCreate
