apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-public
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-blob-public
  storageClassName: azureblob-fuse-premium