apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: azure-disk
    namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi