apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce # Azure Disk chỉ hỗ trợ ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
